name: "Testing workflow"


on:
  push:
    branches:
      - main

jobs:
  test:
    name: "just echo something"
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "hello world"
